services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  aws:
    image: localstack/localstack
    environment:
      LOCALSTACK_SERVICES: apigateway,iam,lambda,s3
    ports:
      - "4566:4566"
      - "4571:4571"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
